name: currency_converter
description: An app to convert between different types of currencies.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  equatable: ^2.0.5
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  firebase_core: ^2.24.2
  get_it: ^7.6.0
  intl: ^0.19.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  j1_lints:
    git:
      url: https://github.com/J1-Apps/j1_lints.git
      ref: v1.0.0

  j1_ui:
    git:
      url: https://github.com/J1-Apps/j1_ui.git
      ref: v1.0.0

  flutter_launcher_icons: ^0.13.1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: JamIcons
      fonts:
        - asset: packages/j1_ui/fonts/JamIcons.ttf