name: currency_converter
description: An app to convert between different types of currencies.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  j1_ui:
    git:
      url: https://github.com/J1-Apps/j1_ui.git
      ref: v1.0.3

  j1_environment:
    git:
      url: https://github.com/J1-Apps/j1_environment.git
      ref: v1.0.0

  j1_theme:
    git:
      url: https://github.com/J1-Apps/j1_theme.git
      ref: v1.0.0

  j1_logger:
    git:
      url: https://github.com/J1-Apps/j1_logger.git
      ref: v1.1.1

  j1_crash_handler:
    git:
      url: https://github.com/J1-Apps/j1_crash_handler.git
      ref: v1.0.1

  j1_router:
    git:
      url: https://github.com/J1-Apps/j1_router.git
      ref: v1.0.2

  firebase_analytics: ^11.2.1
  firebase_crashlytics: ^4.0.4
  firebase_core: ^3.3.0
  get_it: ^7.6.0
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  flutter_bloc: ^8.1.6
  firebase_core_platform_interface: ^5.2.0
  rxdart: ^0.28.0
  http: ^1.2.2
  dart_mappable: ^4.2.2
  shared_preferences: ^2.3.2
  bloc_concurrency: ^0.2.5
  vector_graphics: ^1.1.11+1
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  j1_lints:
    git:
      url: https://github.com/J1-Apps/j1_lints.git
      ref: v1.0.1

  flutter_launcher_icons: ^0.13.1
  mocktail: ^1.0.4
  build_runner: ^2.4.12
  dart_mappable_builder: ^4.2.3
  vector_graphics_compiler: ^1.1.11+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - path: assets/flags/
      transformers:
        - package: vector_graphics_compiler

  fonts:
    - family: JamIcons
      fonts:
        - asset: packages/j1_ui/fonts/JamIcons.ttf

    - family: Abril Fatface
      fonts:
        - asset: fonts/header/AbrilFatface.ttf

    - family: Poppins
      fonts:
        - asset: fonts/body/Poppins-Regular.ttf
        - asset: fonts/body/Poppins-Italic.ttf
          style: italic