// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// coverage:ignore-file
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class TestFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFFPM4Paq09F4FOJwhuY0PRDVJCozUEZw',
    appId: '1:55663510265:web:161620f5d326e3da835828',
    messagingSenderId: '55663510265',
    projectId: 'j1-currency-converter',
    authDomain: 'j1-currency-converter.firebaseapp.com',
    storageBucket: 'j1-currency-converter.firebasestorage.app',
    measurementId: 'G-2XQS4SKGHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL931UI8SQjdejIuEFimkT-6Zg_84ls2A',
    appId: '1:55663510265:android:dde1f2c81eae433b835828',
    messagingSenderId: '55663510265',
    projectId: 'j1-currency-converter',
    storageBucket: 'j1-currency-converter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXpa_CyFPn0QZVO-W-SlognTAvjKgiPpg',
    appId: '1:55663510265:ios:a014b746740b780e835828',
    messagingSenderId: '55663510265',
    projectId: 'j1-currency-converter',
    storageBucket: 'j1-currency-converter.firebasestorage.app',
    iosBundleId: 'com.j1.currencyConverter',
  );
}
