// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// coverage:ignore-file
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class TestFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmTha9C7px-aWdxgfjVgJjcMh9IXKK9Pg',
    appId: '1:1079949704264:web:fb6c22c489f45ac8d62c7d',
    messagingSenderId: '1079949704264',
    projectId: 'currency-converter-test-f28cf',
    authDomain: 'currency-converter-test-f28cf.firebaseapp.com',
    storageBucket: 'currency-converter-test-f28cf.appspot.com',
    measurementId: 'G-GRQ5FXS8QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA10ofh5EPrKl8Vvzkfc2XYXc6URD0gK1o',
    appId: '1:1079949704264:android:8782389dcc96b4c0d62c7d',
    messagingSenderId: '1079949704264',
    projectId: 'currency-converter-test-f28cf',
    storageBucket: 'currency-converter-test-f28cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC38xC_KLLM9-RGfmLdmA8MWd686mI5JkY',
    appId: '1:1079949704264:ios:8be349108aa83924d62c7d',
    messagingSenderId: '1079949704264',
    projectId: 'currency-converter-test-f28cf',
    storageBucket: 'currency-converter-test-f28cf.appspot.com',
    iosBundleId: 'com.j1.currencyConverter',
  );
}
